# Generated by Django 5.0.2 on 2024-02-29 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='biography.experience'),
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
