# Generated by Django 5.0.2 on 2024-02-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_experience_delete_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='project',
            name='read_time',
        ),
        migrations.RemoveField(
            model_name='project',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='project',
            name='updated',
        ),
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(default=None),
        ),
    ]
