# Generated by Django 5.0.2 on 2024-02-29 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['id'], 'verbose_name': 'Biography', 'verbose_name_plural': 'Biography'},
        ),
    ]
