# Generated by Django 5.0.2 on 2024-02-23 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blogpost_blog_post_delete_blog_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name="Post's title",
            new_name='title',
        ),
    ]
